[package]
name = "tester"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.28.0", features = ["full"] }
crdts = { path = "../crdts" }
tonic = "0.9.2"
protocol = { path = "../protocol" }