[package]
name = "crdts"
version = "0.1.0"
edition = "2021"

[dependencies]
sha2 = "0.10"
hex = "0.4"
tracing = "0.1.37"
rand = "0.8.5"
rand_pcg = "0.3.1"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "benchmarks"
harness = false